
package com.micromuse.response.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.micromuse.response.types.ObjectFactory;
import com.micromuse.response.types.PolicyExecutionResult;
import com.micromuse.response.types.WSListenerId;
import com.micromuse.response.types.WSPolicyUserParameter;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImpactWebServiceListenerDLIfc", targetNamespace = "http://response.micromuse.com/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImpactWebServiceListenerDLIfc {


    /**
     * 
     * @param string1
     * @param string2
     * @return
     *     returns com.micromuse.response.types.WSListenerId
     * @throws WSListenerException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://response.micromuse.com/types", className = "com.micromuse.response.types.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://response.micromuse.com/types", className = "com.micromuse.response.types.LoginResponse")
    public WSListenerId login(
        @WebParam(name = "String_1", targetNamespace = "")
        String string1,
        @WebParam(name = "String_2", targetNamespace = "")
        String string2)
        throws WSListenerException
    ;

    /**
     * 
     * @param string2
     * @param wsListenerId1
     * @param arrayOfWSPolicyUserParameter3
     * @param boolean4
     * @return
     *     returns java.util.List<com.micromuse.response.types.PolicyExecutionResult>
     * @throws WSListenerException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "runPolicy", targetNamespace = "http://response.micromuse.com/types", className = "com.micromuse.response.types.RunPolicy")
    @ResponseWrapper(localName = "runPolicyResponse", targetNamespace = "http://response.micromuse.com/types", className = "com.micromuse.response.types.RunPolicyResponse")
    public List<PolicyExecutionResult> runPolicy(
        @WebParam(name = "WSListenerId_1", targetNamespace = "")
        WSListenerId wsListenerId1,
        @WebParam(name = "String_2", targetNamespace = "")
        String string2,
        @WebParam(name = "arrayOfWSPolicyUserParameter_3", targetNamespace = "")
        List<WSPolicyUserParameter> arrayOfWSPolicyUserParameter3,
        @WebParam(name = "boolean_4", targetNamespace = "")
        boolean boolean4)
        throws WSListenerException
    ;

}
