
package com.micromuse.response.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImpactWebServiceListenerDL", targetNamespace = "http://response.micromuse.com/wsdl", wsdlLocation = "file:/C:/ImpactWebServiceListenerDL.wsdl")
public class ImpactWebServiceListenerDL
    extends Service
{

    private final static URL IMPACTWEBSERVICELISTENERDL_WSDL_LOCATION;
    private final static WebServiceException IMPACTWEBSERVICELISTENERDL_EXCEPTION;
    private final static QName IMPACTWEBSERVICELISTENERDL_QNAME = new QName("http://response.micromuse.com/wsdl", "ImpactWebServiceListenerDL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ImpactWebServiceListenerDL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMPACTWEBSERVICELISTENERDL_WSDL_LOCATION = url;
        IMPACTWEBSERVICELISTENERDL_EXCEPTION = e;
    }

    public ImpactWebServiceListenerDL() {
        super(__getWsdlLocation(), IMPACTWEBSERVICELISTENERDL_QNAME);
    }

    public ImpactWebServiceListenerDL(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPACTWEBSERVICELISTENERDL_QNAME, features);
    }

    public ImpactWebServiceListenerDL(URL wsdlLocation) {
        super(wsdlLocation, IMPACTWEBSERVICELISTENERDL_QNAME);
    }

    public ImpactWebServiceListenerDL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPACTWEBSERVICELISTENERDL_QNAME, features);
    }

    public ImpactWebServiceListenerDL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImpactWebServiceListenerDL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImpactWebServiceListenerDLIfc
     */
    @WebEndpoint(name = "ImpactWebServiceListenerDLIfcPort")
    public ImpactWebServiceListenerDLIfc getImpactWebServiceListenerDLIfcPort() {
        return super.getPort(new QName("http://response.micromuse.com/wsdl", "ImpactWebServiceListenerDLIfcPort"), ImpactWebServiceListenerDLIfc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImpactWebServiceListenerDLIfc
     */
    @WebEndpoint(name = "ImpactWebServiceListenerDLIfcPort")
    public ImpactWebServiceListenerDLIfc getImpactWebServiceListenerDLIfcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://response.micromuse.com/wsdl", "ImpactWebServiceListenerDLIfcPort"), ImpactWebServiceListenerDLIfc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPACTWEBSERVICELISTENERDL_EXCEPTION!= null) {
            throw IMPACTWEBSERVICELISTENERDL_EXCEPTION;
        }
        return IMPACTWEBSERVICELISTENERDL_WSDL_LOCATION;
    }

}
