
package com.micromuse.response.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSListenerException", targetNamespace = "http://response.micromuse.com/types")
public class WSListenerException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.micromuse.response.types.WSListenerException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSListenerException(String message, com.micromuse.response.types.WSListenerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSListenerException(String message, com.micromuse.response.types.WSListenerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.micromuse.response.types.WSListenerException
     */
    public com.micromuse.response.types.WSListenerException getFaultInfo() {
        return faultInfo;
    }

}
