
 /**
  * This template file was generated by dynaTrace client.
  * The dynaTrace community portal can be found here: http://community.compuwareapm.com/
  * For information how to publish a plugin please visit http://community.compuwareapm.com/plugins/contribute/
  **/ 

package com.dynatrace.diagnostics.plugin;

import com.dynatrace.diagnostics.pdk.*;

import com.dynatrace.diagnostics.plugin.extendedexecutor.*;

public class NetCoolEventAction extends GenericExecutor implements Action {


	@Override
	public Status setup(ActionEnvironment env) throws Exception {
		return super.setup(env);
	}

	@Override
	public Status execute(ActionEnvironment env) throws Exception {
		return super.execute(env);
	}

	@Override
	public void teardown(ActionEnvironment env) throws Exception {
		super.teardown(env);
	}
}